@echo off
cd /d "%~dp0"
echo Stopping any existing dev server on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000 ^| findstr LISTENING') do taskkill /PID %%a /F >nul 2>&1
echo Starting dev server...
"C:\Program Files\nodejs\npm.cmd" run dev
